print("Welcome to a simple mad libs game.")
print("Pizza was invented by a (adj) (nationality) chef named (person). To make a pizza, you need to take a lump of (noun), and make a thin, round (adj) (noun). Then you cover it with (adj), sauce (adj) cheese, and fresh chopped. Next you have to bake it in a very hot (noun). When it is done, cut it into (number) (shapes). Some kids like (food) pizza the best, but my favorite is the (food) pizza. If i could, I would eat pizza (number) times a day.")

a = input('Give me the first adjectives')
nat = input('Give me a nationality')
per = input('Give me a person')
n = input('Give me a noun')
a2 = input('Give me a second adjectives ')
n2 = input('Give me a second noun')
a3 = input('Give me a thrid adjective')
a4 = input('Give me a fourth adjective')
pn= input('Give me a plural noun')
n3 = input('Give me a third noun')
num = input('Give me an number')
shapes = input('Give me a shape')
food = input('Give me a food')
food2 = input('Give me a second food')
num2 = input ('Give me a second number')
print("Pizza was invented by a %s %s chef named %s. To make a pizza, you need to take a lump of %s, and make a thin, round %s %s. Then you cover it with %s sauce, %s cheese, and fresh chopped %ss. Next you have to bake it in a very hot %s. When it is done, cut it into %s %s. Some kids like %s pizza the best, but my favorite is the %s pizza. If i could, I would eat pizza %s times a day." % (a,nat,per,n,a2,n2,a3,a4,pn,n3,num,shapes,food,food2,num2) )
